#! /usr/bin/expect
# usage: this script can accept args, e.g. 
#   ./3_auto_login_and_exec_cmd_with_args.exp root 192.168.3.175 date
# date: 2016-04-06 20:55
# author: ChangFeng.ch

set user [lindex $argv 0]
set host [lindex $argv 1]
set cmd  [lindex $argv 2]
set passwd "lyys"

spawn ssh -l $user $host 

expect {
    "yes/no:" { send "yes\r" }
    "password:" { send "$passwd\r" }
}

expect "]*"
    send "$cmd\r"

expect "]*"
    send "exit\r"
